title: "[Support]: "
labels: [support]

body:
  - type: markdown
    attributes:
      value: |
        Note: Search to make sure that your question wasn't asked before.
        
        You can include screen-shots or gifs.

        Please use https://mclo.gs/ for any config's / files or errors.
  - type: dropdown
    id: plugin
    attributes:
      label: Server Plugin
      description: Which plugin are you asking for support with?
      options:
        - CrazyCrates
        - CrazyEnvoys
        - CrazyVouchers
        - CrazyEnchantments
        - CrazyAuctions
        - ChatManager
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the you need help with.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I have searched for and ensured there isn't already an open issue regarding this.
          required: true
        - label: I ticked all the boxes without actually reading them
          required: false
        - label: My version of Minecraft is supported by CrazyCrew.
          required: true